### ISSUE TITLE
Did you fix persistant cron jobs?

### ISSUE THREAD

**Issue by JamesValero** [baroka/idrive#1]
Just noticed this was removed from the README. Were these fixed? I didn't see the IDrive service auto-start after restarting the docker container. Thanks for providing this container!

```
SECOND RUN AND SUCCESSIVES
 - IDrive CRON and dashboard daemon don't persist when you stop and run again the container. 
   It's necessary to execute again ./account_setting.pl (no need to reconfigure, only restart services). 
TODO
 - Persist cron and dashboard IDrive daemon. I tried with expect commando but no luck. 
```

**Comment by baroka** [comment]
Sorry, not really... I thought it was fixed but no luck. I just add comments again.
