### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by psperry** [baroka/idrive#3]
Spent a few minutes and go this running and it works great! I can't really put it into production though until it can be restarted without manual intervention. 

Is this still a work in progress?

**Comment by baroka** [comment]
Sorry, I couldn't figure out how to do it. I only run a backup once a month, so it isn't a must-have for me.

**Comment by psperry** [comment]
Fair enough. Thanks for the reply.  I've been doing some research and thought maybe I'd give this a shot. I will be sure to share if I figure it out.
